### ISSUE TITLE
Fetching data from Youtube

### ISSUE THREAD

**Issue by ilyassFouih** [ngMorocco/ngx-darija#3]
We need to know how to fetch Angular in Darija videos from Youtube (check the Youtube API)

**Comment by ilyassFouih** [comment]
[Youtube playlists API](https://developers.google.com/youtube/v3/guides/implementation/playlists)

**Comment by ayoub-bani** [comment]
how the videos will be implemented 
because in the sketch i supposed that you have a broadcasting platform 
or just remove the player from the hero section and add the videos as a playlist using the api

**Comment by ilyassFouih** [comment]
> how the videos will be implemented
> because in the sketch i supposed that you have a broadcasting platform
> or just remove the player from the hero section and add the videos as a playlist using the api

I think we can use the Youtube player for `angular in darija` playlists. 
And for the hero section, we can put the last episode with a Youtube player in the background.

Got me thinking of adding a new section where we can watch live a session if it's being broadcasted on Youtube.

What do u think?

**Comment by ayoub-bani** [comment]
> > how the videos will be implemented
> > because in the sketch i supposed that you have a broadcasting platform
> > or just remove the player from the hero section and add the videos as a playlist using the api
> 
> I think we can use the Youtube player for `angular in darija` playlists.
> And for the hero section, we can put the last episode with a Youtube player in the background.
> 
> Got me thinking of adding a new section where we can watch live a session if it's being broadcasted on Youtube.
> 
> What do u think?

yeah good  idea just gonna know how it will be implemented 
or a navbar button activated and animated when a live is broadcasted that refer to the youtube live, also if no live are available we can show a little info about when the next live will be like a popover
and add a separated root for live and previous broadcast instead of injecting all the content in the home page 

<img src="https://vectorency.com/wp-content/uploads/2020/11/Live-buttons-svg.jpg" width="200" height="200" />
